# ---------- BUILD STAGE ----------
FROM quay.io/keycloak/keycloak:26.4.7 AS builder

WORKDIR /opt/keycloak

# Import realm + users
COPY keycloak-export/ /opt/keycloak/data/import/

# Build optimized Keycloak (MANDATORY in 26+)
RUN /opt/keycloak/bin/kc.sh build

# ---------- RUNTIME STAGE ----------
FROM quay.io/keycloak/keycloak:26.4.7

WORKDIR /opt/keycloak

# Copy built server
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENV KC_DB=postgres
ENV KC_PROXY=edge
ENV KC_HTTP_ENABLED=true
ENV KC_HTTP_PORT=8080
ENV KC_HOSTNAME_STRICT=false

EXPOSE 8080

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start", "--import-realm"]
