eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/fitness-app
          jwk-set-uri: http://localhost:8181/realms/fitness-app/protocol/openid-connect/certs


  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**

            - id: activity-service
              uri: lb://ACTIVITY-SERVICE
              predicates:
                - Path=/api/activities/**

            - id: ai-service
              uri: lb://AI-SERVICE
              predicates:
                - Path=/api/recommendations/**

            - id: notificationservice
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/notifications/**
              filters:
                - StripPrefix=1

keycloak:
  auth-server-url: http://localhost:8181
  realm: fitness-app
  admin:
    client-id: admin-cli
    client-secret: ${KEYCLOAK_ADMIN_PASSWORD}
    username: admin
    password: admin
  registration:
    enabled: true
    email-verification-required: true
    default-role: USER

server:
  port: 8084