spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-micro-user
    username: admin
    password: admin@123

  jpa:
    hibernate:
      ddl-auto: update  # Automatically update the database schema, not delete data just update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
        #register-with-eureka: true
        #fetch-registry: true

server:
  port: 8081